### ISSUE TITLE
fix the medals

### ISSUE THREAD

**Issue by SakuruWasTaken** [osuHOW/lets#13]

**Comment by Hubza** [comment]
please

**Comment by SakuruWasTaken** [comment]
this probably won't happen for a very long time, at least not with help

**Comment by SakuruWasTaken** [comment]
bumped to high priority, i'll start working on it this morning

**Comment by SakuruWasTaken** [comment]
they're still broken

**Comment by Hubza** [comment]
![screenshot951](https://user-images.githubusercontent.com/33783503/177418324-4058ece1-51cb-45d5-8024-71eb73cc8c99.png)

you sure?

**Comment by SakuruWasTaken** [comment]
the icons are wrong and it enters the wrong achievement into the datebase

**Comment by SakuruWasTaken** [comment]
accidentally closed

**Comment by SakuruWasTaken** [comment]
i'll likely port over gulag's code for achievements, as it is much better and easier to work with

**Comment by SakuruWasTaken** [comment]
backend code is fixed, not all achievements are working though
